### ISSUE TITLE
Claim fail with following error

### ISSUE THREAD

**Issue by phamhphuc** [Cra5hs/bot_claim_simbaempire#1]
Sometimes it work but some times it show this error as below
[https://i.imgur.com/cE2YndP.png](url)

Anyway we can fix this?

Thanks

**Comment by 0xcra5hs** [comment]
Your transaction committed, and its pending state. U need waitting to transaction is confirmed.

So, bot will call contract continuous for make sure never missing. You can increase gasPrice this transaction to speed up.

Sample:
gasPrice: gasPrice * 20;
